# BUILD
# Keep necessary exports if other packages need the bzl file itself
exports_files([
    "cc_mini_toolchain.bzl",
    "toolchains.MODULE.bazel",
])  # Or the old one if you keep it temporarily

package(default_visibility = ["//visibility:public"])
